[xdebug]
xdebug.mode=debug
xdebug.start_with_request=yes
# Usa host.docker.internal para conectar con Windows
xdebug.client_host=host.docker.internal
xdebug.client_port=9003
xdebug.discover_client_host=0
xdebug.log=/tmp/xdebug.log
xdebug.idekey=VSCODE
# AÑADE ESTO: Para darle más tiempo a la conexión
xdebug.connect_timeout_ms=2000